version: "3.9"
services:
  my_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - $HOME/Desktop/host_volume:/home/app/volume
    links:
      - my_mongo
  my_mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_password