version: "3.9"
services:
  myapp:
    # build: .
    # context: .
    # dockerfile: Dockerfile.dev
    image: orpimel/desafio_8:v1.0.0
    ports:
      - "3000:3000"
    volumes:
      - $HOME/Desktop/host_volume:/home/app/volume
      # - .:/home/app
  mongo-service:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: my_user
      MONGO_INITDB_ROOT_PASSWORD: my_password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: