apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
  namespace: desafio9
spec:
  source:
    path: Solucion_Desafio_9/minikube
    repoURL: https://github.com/BambooThink/BootcampDevOps2023
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default