- name: Install Grafana, Prometheus, Node Exporter
  hosts: debian
  become: true
  tasks:
  
    - name: repository configuration
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present
        autoclean: yes

    - name: install grafana
      become: yes
      ansible.builtin.import_tasks: packages/grafana.yml
      tags: [install grafana]
    
    - name: install prometheus
      become: yes
      ansible.builtin.import_tasks: packages/prometheus.yml
      tags: [install prometheus]
    
    - name: install node_exporter
      become: yes
      ansible.builtin.import_tasks: packages/node_exporter.yml
      tags: [install node_exporter]
  