- name: Install Grafana, Prometheus
  hosts: ubuntu
  become: true
  tasks:
  
    - name: Repository Configuration
      apt:
        name:
          - apt-transport-https
          - software-properties-common
        state: present
        autoclean: yes

    - name: Install Grafana
      become: yes
      ansible.builtin.import_tasks: packages/grafana.yml
      tags: [install grafana]
    
    - name: Install Prometheus
      become: yes
      ansible.builtin.import_tasks: packages/prometheus.yml
      tags: [install prometheus]

- name: Install Prometheus Node Exporter
  hosts: debian
  become: true
  tasks:

    - name: Install node_exporter
      become: yes
      ansible.builtin.import_tasks: packages/node_exporter.yml
      tags: [install node_exporter]
  