apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: desafio8
  labels:
    app: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi